# This workflow will run make reviewable and make check-diff as checks

name: Reviewable&Check-Diff

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  GO_IMPORT_VERSION: 'v0.16.1'

jobs:
  reviewable-checkdiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: '1.26'

    - name: Install go imports
      run: |
        cd /tmp
        go install golang.org/x/tools/cmd/goimports@${{ env.GO_IMPORT_VERSION }}

    - name: Make Reviewable
      run: make reviewable
      # env:
      #   RUNNING_IN_CI: 'true'
    - name: Make Check-Diff
      run: make check-diff
